In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ipywidgets import interact, interact_manual

In [2]:
#Import clean datasaet
X = pd.read_csv('X_clean.csv')
y = pd.read_csv('y_clean.csv')

In [3]:
#Splitting dataset into the training data and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [4]:
X

0  1  2  3   4  5  14  15      17       18  ...  10_2  11_1  11_2  12_1  \
0     0  0  1  0   1  0   0   1   29.85    29.85  ...     0     0     0     0   
1     1  0  0  0  34  1   1   0   56.95  1889.50  ...     1     0     0     0   
2     1  0  0  0   2  1   0   1   53.85   108.15  ...     0     0     0     0   
3     1  0  0  0  45  0   1   0   42.30  1840.75  ...     1     0     1     0   
4     0  0  0  0   2  1   0   1   70.70   151.65  ...     0     0     0     0   
...  .. .. .. ..  .. ..  ..  ..     ...      ...  ...   ...   ...   ...   ...   
7027  1  0  1  1  24  1   1   1   84.80  1990.50  ...     1     0     1     0   
7028  0  0  1  1  72  1   1   1  103.20  7362.90  ...     1     0     0     0   
7029  0  0  1  1  11  0   0   1   29.60   346.45  ...     0     0     0     0   
7030  1  1  1  0   4  1   0   1   74.40   306.60  ...     0     0     0     0   
7031  1  0  0  0  66  1   2   1  105.65  6844.50  ...     1     0     1     0   

      12_2  13_1  13_2  16_1  16_2  16_3  
0        0     0     0     0     1     0  
1        0     0     0     0     0     1  
2        0     0     0     0     0     1  
3        0     0     0     0     0     0  
4        0     0     0     0     1     0  
...    ...   ...   ...   ...   ...   ...  
7027     1     0     1     0     0     1  
7028     1     0     1     1     0     0  
7029     0     0     0     0     1     0  
7030     0     0     0     0     0     1  
7031     1     0     1     0     0     0  

[7032 rows x 29 columns]

In [5]:
y

0
0     0
1     0
2     1
3     0
4     1
...  ..
7027  0
7028  0
7029  0
7030  1
7031  0

[7032 rows x 1 columns]

In [6]:
X_train

0  1  2  3   4  5  14  15      17       18  ...  10_2  11_1  11_2  12_1  \
2959  1  0  1  0  24  1   1   1   58.35  1346.90  ...     0     0     1     0   
5105  0  0  1  1  71  1   2   0  113.65  8166.80  ...     1     0     1     0   
5354  1  0  1  1  70  1   2   0   25.35  1715.15  ...     0     1     0     1   
5066  0  0  0  1  49  1   1   0   19.45   921.30  ...     0     1     0     1   
156   0  0  0  0  22  1   0   1   84.15  1821.95  ...     0     0     0     0   
...  .. .. .. ..  .. ..  ..  ..     ...      ...  ...   ...   ...   ...   ...   
4931  1  0  0  0   1  1   0   0   18.90    18.90  ...     0     1     0     1   
3264  1  0  0  0  65  1   1   0   24.80  1600.95  ...     0     1     0     1   
1653  1  0  1  1  50  1   0   0  105.95  5341.80  ...     1     0     0     0   
2607  0  0  1  1  14  1   0   0   80.45  1137.05  ...     0     0     1     0   
2732  1  0  0  0  64  1   1   1  104.65  6889.80  ...     1     0     1     0   

      12_2  13_1  13_2  16_1  16_2  16_3  
2959     0     0     0     0     1     0  
5105     1     0     1     1     0     0  
5354     0     1     0     0     0     1  
5066     0     1     0     1     0     0  
156      1     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4931     0     1     0     0     0     1  
3264     0     1     0     1     0     0  
1653     1     0     1     1     0     0  
2607     1     0     1     1     0     0  
2732     1     0     1     1     0     0  

[5625 rows x 29 columns]

In [7]:
X_test

0  1  2  3   4  5  14  15      17       18  ...  10_2  11_1  11_2  12_1  \
5552  1  0  0  0   1  1   0   0   20.65    20.65  ...     0     1     0     1   
5805  1  0  0  0  16  1   0   1   20.60   330.25  ...     0     1     0     1   
2640  0  0  0  0   1  1   0   0   19.80    19.80  ...     0     1     0     1   
3976  1  0  0  0   1  0   0   1   24.25    24.25  ...     0     0     0     0   
6429  1  1  0  0   1  1   0   1   74.40    74.40  ...     0     0     0     0   
...  .. .. .. ..  .. ..  ..  ..     ...      ...  ...   ...   ...   ...   ...   
2752  0  0  1  1  69  1   1   0   84.45  5848.60  ...     1     0     0     0   
5693  1  1  1  1  71  1   0   1  105.10  7548.10  ...     0     0     0     0   
1657  1  0  0  0   5  1   0   1   69.75   324.60  ...     0     0     0     0   
2761  0  0  1  0  64  1   1   1  115.00  7396.15  ...     1     0     1     0   
2913  1  1  1  0   8  0   0   1   43.35   371.40  ...     1     0     0     0   

      12_2  13_1  13_2  16_1  16_2  16_3  
5552     0     1     0     0     1     0  
5805     0     1     0     1     0     0  
2640     0     1     0     1     0     0  
3976     0     0     0     0     1     0  
6429     0     0     0     0     1     0  
...    ...   ...   ...   ...   ...   ...  
2752     0     0     0     0     0     0  
5693     1     0     1     1     0     0  
1657     0     0     0     0     1     0  
2761     1     0     1     0     1     0  
2913     0     0     1     0     0     1  

[1407 rows x 29 columns]

In [8]:
y_train

0
2959  0
5105  0
5354  0
5066  0
156   0
...  ..
4931  0
3264  0
1653  1
2607  0
2732  0

[5625 rows x 1 columns]

In [9]:
y_test

0
5552  0
5805  0
2640  0
3976  1
6429  1
...  ..
2752  0
5693  1
1657  1
2761  0
2913  0

[1407 rows x 1 columns]

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
X_train

array([[ 0.99485767, -0.43730142,  1.03898144, ..., -0.52489066,
         1.39574826, -0.54276283],
       [-1.00516891, -0.43730142,  1.03898144, ...,  1.90515869,
        -0.71646158, -0.54276283],
       [ 0.99485767, -0.43730142,  1.03898144, ..., -0.52489066,
        -0.71646158,  1.84242537],
       ...,
       [ 0.99485767, -0.43730142,  1.03898144, ...,  1.90515869,
        -0.71646158, -0.54276283],
       [-1.00516891, -0.43730142,  1.03898144, ...,  1.90515869,
        -0.71646158, -0.54276283],
       [ 0.99485767, -0.43730142, -0.9624811 , ...,  1.90515869,
        -0.71646158, -0.54276283]])

In [12]:
X_test

array([[ 0.99485767, -0.43730142, -0.9624811 , ..., -0.52489066,
         1.39574826, -0.54276283],
       [ 0.99485767, -0.43730142, -0.9624811 , ...,  1.90515869,
        -0.71646158, -0.54276283],
       [-1.00516891, -0.43730142, -0.9624811 , ...,  1.90515869,
        -0.71646158, -0.54276283],
       ...,
       [ 0.99485767, -0.43730142, -0.9624811 , ..., -0.52489066,
         1.39574826, -0.54276283],
       [-1.00516891, -0.43730142,  1.03898144, ..., -0.52489066,
         1.39574826, -0.54276283],
       [ 0.99485767,  2.28675226,  1.03898144, ..., -0.52489066,
        -0.71646158,  1.84242537]])

In [13]:
#importing keras
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [14]:
#initialising ANN
classifier = Sequential()

#input layer and first hiden layer
classifier.add(Dense(output_dim=15, init ='uniform',activation='relu', input_dim=29))

#input second layer
classifier.add(Dense(output_dim=15, init ='uniform',activation='relu'))

#output layer
classifier.add(Dense(output_dim=1, init ='uniform',activation='sigmoid'))

#compile ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

C:\Users\wisnu\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=29, units=15, kernel_initializer="uniform")`
  """
C:\Users\wisnu\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=15, kernel_initializer="uniform")`
  
C:\Users\wisnu\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()


In [15]:
classifier.fit(X_train,y_train, batch_size=10, nb_epoch=100)

C:\Users\wisnu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
5625/5625 [==============================] - 1s 239us/step - loss: 0.4822 - accuracy: 0.7732
Epoch 2/100
5625/5625 [==============================] - 1s 205us/step - loss: 0.4248 - accuracy: 0.7982
Epoch 3/100
5625/5625 [==============================] - 1s 210us/step - loss: 0.4186 - accuracy: 0.8041
Epoch 4/100
5625/5625 [==============================] - 1s 226us/step - loss: 0.4166 - accuracy: 0.8021
Epoch 5/100
5625/5625 [==============================] - 1s 221us/step - loss: 0.4158 - accuracy: 0.8004
Epoch 6/100
5625/5625 [==============================] - 1s 216us/step - loss: 0.4142 - accuracy: 0.8018
Epoch 7/100
5625/5625 [==============================] - 1s 221us/step - loss: 0.4137 - accuracy: 0.8034
Epoch 8/100
5625/5625 [==============================] - 1s 221us/step - loss: 0.4138 - accuracy: 0.8028
Epoch 9/100
5625/5625 [==============================] - 1s 224us/step - loss: 0.4121 - accuracy: 0.8055
Epoch 10/100
5625/5625 [==============================]

5625/5625 [==============================] - 1s 188us/step - loss: 0.3813 - accuracy: 0.8256
Epoch 79/100
5625/5625 [==============================] - 1s 183us/step - loss: 0.3807 - accuracy: 0.8213
Epoch 80/100
5625/5625 [==============================] - 1s 179us/step - loss: 0.3796 - accuracy: 0.8208
Epoch 81/100
5625/5625 [==============================] - 1s 185us/step - loss: 0.3806 - accuracy: 0.8217
Epoch 82/100
5625/5625 [==============================] - 1s 183us/step - loss: 0.3794 - accuracy: 0.8238
Epoch 83/100
5625/5625 [==============================] - 5s 884us/step - loss: 0.3809 - accuracy: 0.8251
Epoch 84/100
5625/5625 [==============================] - 4s 702us/step - loss: 0.3792 - accuracy: 0.8235
Epoch 85/100
5625/5625 [==============================] - ETA: 0s - loss: 0.3799 - accuracy: 0.82 - 3s 541us/step - loss: 0.3796 - accuracy: 0.8260
Epoch 86/100
5625/5625 [==============================] - 3s 597us/step - loss: 0.3785 - accuracy: 0.8235
Epoch 87/100
5625

In [16]:
#predict
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5)

In [17]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [18]:
cm

array([[947,  91],
       [208, 161]], dtype=int64)